version: '3'
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - ./db/.env
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./db/.env
    ports:
      - "3030:3030"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:3030/healthcheck"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  postgres_data:
