version: '3'
services:
  
  nest-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - postgres

  postgres:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
