version: '3'
services:
  nest-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: nestjs_app
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
