version: '3'
services:
  db:
    container_name: chatDB
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - ./db/.env
    volumes:
      - /var/docker/postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: chatApi
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./app/.env
    ports:
      - "3030:3030"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3030/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
