version: '3'
services:
  postgres:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nest-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - ./db/.env
    ports:
      - "80:3000"
    depends_on:
      postgres:
        condition: service_healthy


volumes:
  postgres_data:
