name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build . --file app/Dockerfile --tag chatapi:latest

    # - name: Log in to Docker Hub
    #   run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    # - name: Push Docker Image to Docker Hub
    #   run: docker push kunohdere/chatapi:latest
