name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]  # Corrected Node.js version

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      run: |
        npm ci
        npm run build --if-present
        npm test

    - name: Build Docker Image
      run: |
        docker build . --file app/Dockerfile --tag chatapi:latest

    # - name: Log in to Docker Hub
    #   run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    # - name: Push Docker Image to Docker Hub
    #   run: docker push kunohdere/chatapi:latest
